#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    echo 'magento-docker must be run as a CLI application';
    exit(1);
}

define('ROOT', dirname(__FILE__));

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/app/autoload.php';

use Console\App;
use Console\Utils\Registry;

$handler = function ($signal) {
    switch($signal) {
        case SIGTERM:
            print "Caught SIGTERM\n";
            break;
        case SIGKILL:
            print "Caught SIGKILL\n";
            break;
        case SIGINT:
            print "Caught SIGINT\n";
            Registry::set('exit', true);
            $stream = Registry::get('stream');
            fclose($stream);
            var_dump($stream);

            break;
    }
};
pcntl_signal(SIGINT, $handler);

$dockerApp = new App();

try {
    $dockerApp->launch();
} catch (\Throwable $e) {
    echo $e->getMessage();
    exit(1);
}
